baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Anthropomorphic'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
